project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

project/mysite/pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/answer/create/', views.answer_create, name='answer_create'),
]

project/mysite/pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

project/mysite/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .models import Question


# Create your views here.
def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list':question_list}
    return render(request, 'myapp/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'myapp/question_detail.html', {'question':question})

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('pybo:detail', question_id=question_id)

project/mysite/templates/myapp/question_detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>Question : {{ question.subject }}</title>
    </head>
    <body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
    </body>
</html>

project/mysite/templates/myapp/question_list.html
<!DOCTYPE html>
<html>
    <head>
        <title>This is pybo!</title>
    </head>
    <body>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
      
        {% comment %} <h1> Pybo 게시판 </h1>
        {% if question_list %}
        <ul>
            {% for question in question_list %}
            <a href='{% url 'pybo:detail' question.id %}'><li>{{ question.subject }}</li>
            {% endfor %}
        </ul>
        {% else %}
        <p> 게시판이 비어있습니다. </p>
        {% endif %} {% endcomment %}

        <div class="container my-3">
            <table class="table">
                <thead><!-- 이러한 방식으로 헤드를 구성할 수 도 있는가보다. -->
                <tr class="thead-black">
                    <th>번호</th><!-- 1,1 -->
                    <th>제목</th><!-- 1,2 -->
                    <th>작성일시</th><!-- 1,3 -->
                </tr>
                <thead>
                <tbody><!-- table의 body를 구성 -->
                {% if question_list %}
                {% for question in question_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                    </td>
                    <td>{{ question.create_date }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">질문이 없습니다.</td>
                </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </body>
</html>