복습용_데이터저장/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

복습용_데이터저장/pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
]

복습용_데이터저장/pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

복습용_데이터저장/pybo/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question

# Create your views here.
def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list':question_list}
    return render(request, 'myapp/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answer_list = question.answer_set.all()
    context = {'question':question, 'answer_list':answer_list}
    return render(request, 'myapp/question_detail.html', context)

복습용_데이터저장/templates/myapp/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>This is pybo!</title>
    </head>
    <body>
        <h1> Pybo 게시판 </h1>
        {% if question_list %}
        <ul>
            {% for question in question_list %}
            <a href='{% url 'pybo:detail' question.id %}'><li>{{ question.subject }}</li>
            {% endfor %}
        </ul>
        {% else %}
        <p> 게시판이 비어있습니다. </p>
        {% endif %}
    </body>
</html>

복습용_데이터저장/templates/myapp/question_detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>Question : {{ question.subject }}</title>
    </head>
    <body>
        <h1> {{ question.subject }} </h1>
        <div id='content'>
            {{ question.content }}
        </div>
        <p>--------------------------------------------------</p>
        {% for answer in answer_list %}
            <h3>{{ forloop.counter }} 발행일 : {{ answer.create_date }}</h3>
            {{ answer.content }}
            <p>--------</p>
        {% endfor %}
    </body>
</html>